version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - mkdir -p output
      - cp -r dist/* output/
      - cp appspec.yml output/
      - cp -r scripts output/
      - cp package.json output/

artifacts:
  base-directory: output
  files:
    - '**/*'




# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18.20.5

#     commands:
#       - npm install

#   build:
#     commands:
#       # run build script
#       - npm run build

# artifacts:
#   base-directory: dist
#   files:
#     - "**/*"
# # artifacts:
# #   # include all files required to run the application
# #   files:
# #     - dist//*
# #     #- src//*
# #     - package.json
# #     - appspec.yml
# #     - scripts//*
# #   base-directory: .
