version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.20.5

    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Build complete. Preparing artifacts...

artifacts:
  # include all files required to run the application
  files:
    - dist/**/*
    #- src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*